<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Doclayer</AssemblyName>
    <RootNamespace>WordBarcodeStudio</RootNamespace>
    <AssemblyTitle>Doclayer</AssemblyTitle>
    <Product>Doclayer</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpVectors.Reloaded" Version="1.7.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\logo.svg" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
